### ISSUE TITLE
 i cant run your project why?please help me

### ISSUE THREAD

**Issue by saeidshirazi** [delitamakanda/my-elearning#1]
**(eLearning)undercover@Shadow:~/Desktop/All_IN_One/elearning$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/undercover/.local/share/virtualenvs/eLearning-FDkv-2uL/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/undercover/.local/share/virtualenvs/eLearning-FDkv-2uL/lib/python3.6/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/undercover/.local/share/virtualenvs/eLearning-FDkv-2uL/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/undercover/.local/share/virtualenvs/eLearning-FDkv-2uL/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/undercover/.local/share/virtualenvs/eLearning-FDkv-2uL/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/undercover/.local/share/virtualenvs/eLearning-FDkv-2uL/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/undercover/Desktop/All_IN_One/elearning/myelearning/settings.py", line 25, in <module>
    SECRET_KEY = config('SECRET_KEY')
  File "/home/undercover/.local/share/virtualenvs/eLearning-FDkv-2uL/lib/python3.6/site-packages/decouple.py", line 197, in __call__
    return self.config(*args, **kwargs)
  File "/home/undercover/.local/share/virtualenvs/eLearning-FDkv-2uL/lib/python3.6/site-packages/decouple.py", line 85, in __call__
    return self.get(*args, **kwargs)
  File "/home/undercover/.local/share/virtualenvs/eLearning-FDkv-2uL/lib/python3.6/site-packages/decouple.py", line 70, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.
**

**Comment by delitamakanda** [comment]
Hello,

You don't have a *.env* file inside the root project beside *manage.py*

**Comment by delitamakanda** [comment]
template for the *.env*

```
SECRET_KEY=<your_dummy_secret_key>
DEBUG=True
```

**Comment by delitamakanda** [comment]
close for inactivity
